------------------------------------------------------------------------ r6434 | blueswir1 | 2009-01-24 21:19:18 +0100 (Sa, 24 Jan 2009) | 1 line
Fix bsd-user compile like r6412
------------------------------------------------------------------------
r6435 | malc | 2009-01-25 11:56:48 +0100 (So, 25 Jan 2009) | 1 line

Massage PPC version of cpu_get_real_ticks a little
------------------------------------------------------------------------
r6436 | malc | 2009-01-25 11:56:51 +0100 (So, 25 Jan 2009) | 1 line

Add static qualifier to local functions
------------------------------------------------------------------------
r6437 | aurel32 | 2009-01-26 11:22:15 +0100 (Mo, 26 Jan 2009) | 11 lines

target-ppc: always load kernel to KERNEL_LOAD_ADDR

Linux changed its physical address location in the elf header from
0xc0000000 to 0 on 2.6.25, causing later kernels to fail booting
with the -kernel option.

This patch assures that the lowest segment in the elf binary is loaded
to KERNEL_LOAD_ADDR, which is where the firmware expects it.

Signed-off-by: Alexander Graf <agraf@suse.de>
Signed-off-by: Aurelien Jarno <aurelien@aurel32.net>
------------------------------------------------------------------------
r6438 | aliguori | 2009-01-26 16:22:41 +0100 (Mo, 26 Jan 2009) | 7 lines

Use macros for virtio-net PCI vendor/device IDs (Mark McLoughlin)

Gerd added these macros a while back.

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6439 | aliguori | 2009-01-26 16:22:46 +0100 (Mo, 26 Jan 2009) | 7 lines

Add macro for virtio-console PCI device ID (Mark McLoughlin)

Also use the existing macro for the PCI vendor ID

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6440 | aliguori | 2009-01-26 16:22:57 +0100 (Mo, 26 Jan 2009) | 32 lines

Use the default subsystem vendor ID for virtio  devices (Mark McLoughlin)

A subsystem vendor ID of zero isn't allowed, so we use our
default ID.

Gerd points out that although the PCI subsystem vendor ID is
treated by the guest as the virtio vendor ID:

   /* we use the subsystem vendor/device id as the virtio vendor/device
    * id.  this allows us to use the same PCI vendor/device id for all
    * virtio devices and to identify the particular virtio driver by
    * the subsytem ids */
    vp_dev->vdev.id.vendor = pci_dev->subsystem_vendor;
    vp_dev->vdev.id.device = pci_dev->subsystem_device;

it looks like only the device ID is used right now:

   # grep virtio modules.alias
   alias virtio:d00000001v* virtio_net
   alias virtio:d00000002v* virtio_blk
   alias virtio:d00000003v* virtio_console
   alias virtio:d00000004v* virtio-rng
   alias virtio:d00000005v* virtio_balloon
   alias pci:v00001AF4d*sv*sd*bc*sc*i* virtio_pci
   alias virtio:d00000009v* 9pnet_virtio

so setting the subsystem vendor id to something != zero shouldn't cause
trouble.

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6441 | aliguori | 2009-01-26 16:37:30 +0100 (Mo, 26 Jan 2009) | 14 lines

vnc fixes and improvements (Stefano Stabellini)

this patch fixes a bug and improves the generic pixel conversion
function in vnc.c.
The bug is that when a new vnc client connects we need to reset the flag
has_WMVi but currently we don't.
The generic pixel conversion function is vnc_convert_pixel and currently
is not very efficient since uses the division and multiplication
operators.
To make it more efficient I changed to use bit shift operators instead.

Signed-off-by: Stefano Stabellini <stefano.stabellini@eu.citrix.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6442 | aliguori | 2009-01-26 16:37:35 +0100 (Mo, 26 Jan 2009) | 12 lines

Define PCI vendor and device IDs in pci.h (Stuart Brady)

This patch defines PCI vendor and device IDs in pci.h (matching those
from Linux's pci_ids.h), and uses those definitions where appropriate.

Change from v1:
  Introduces pci_config_set_vendor_id() / pci_config_set_device_id()
  accessors as suggested by Anthony Liguori.

Signed-off-by: Stuart Brady <stuart.brady@gmail.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6443 | aliguori | 2009-01-26 16:37:40 +0100 (Mo, 26 Jan 2009) | 12 lines

Enabled building of x86_64 code on Mac OS X (Alexander Graf)

Mac OS X 10.5 supports 64-bit userspace on an x86_64 kernel and
by default uses 32-bit userspace applications, so the detection for
the host architecture fails.

This patch enabled building of x86_64 code on x86_64 capable CPUS
with Mac OS X.

Signed-off-by: Alexander Graf <agraf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6444 | aliguori | 2009-01-26 16:37:44 +0100 (Mo, 26 Jan 2009) | 7 lines

Handle link status in qemu_sendv_packet() (Mark McLoughlin)

If link is down, pretend that the packet has been successfully sent.

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6445 | aliguori | 2009-01-26 16:57:52 +0100 (Mo, 26 Jan 2009) | 7 lines

Add reset irq state for ps2 reboot callback (Dor Laor)

Should solve 100% cpu ioport poll after reboot.

Signed-off-by: Dor Laor <dor@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6446 | aliguori | 2009-01-26 18:07:42 +0100 (Mo, 26 Jan 2009) | 10 lines

Move definition of rgb_to_pixel_dup_table (Nathan Froyd)

This fixes the warning:

/scratch/froydnj/qemu.git/hw/vga.c:1515: warning: redundant redeclaration of 'rgb_to_pixel_dup_table'
/scratch/froydnj/qemu.git/hw/vga.c:1248: warning: previous declaration of 'rgb_to_pixel_dup_table' was here

Signed-off-by: Nathan Froyd <froydnj@codesourcery.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6447 | aliguori | 2009-01-26 18:07:46 +0100 (Mo, 26 Jan 2009) | 13 lines

build system: Further improve quiet mode (Jan Kiszka)

Derived from Stuart Brady's patch: Show the target directory as prefix
to the current module when building in quiet mode. This helps to gain
overview of the current build progress, specifically when running
parallelized builds.

Furthermore, suppress make command echoing when entering subdirs and
replace $(subst subdir-,,$@) with $* in the related rule.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6448 | aliguori | 2009-01-26 18:17:52 +0100 (Mo, 26 Jan 2009) | 5 lines

qemu iovec: keep track of total size, allow partial copies (Gerd Hoffman)

Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6449 | aliguori | 2009-01-26 18:53:04 +0100 (Mo, 26 Jan 2009) | 40 lines

MTRR support on x86 (Carl-Daniel Hailfinger)

The current codebase ignores MTRR (Memory Type Range Register)
configuration writes and reads because Qemu does not implement caching.
All BIOS/firmware in know of for x86 do implement a mode called
Cache-as-RAM (CAR) which locks down the CPU cache lines and uses the CPU
cache like RAM before RAM is enabled. Qemu assumes RAM is accessible
from the start, but it would be nice to be able to run real
BIOS/firmware in Qemu. For that, we need CAR support and for CAR support
we have to support MTRRs.

This patch is a first step in that direction. MTRRs are MSRs supported
by all recent x86 CPUs, even old i586. Besides influencing cache, the
MTRRs can be written and read back, so discarding MTRR writes violates
the expectations of existing code out there.

An added benefit of this patch is that it fixes the following Linux
kernel error message present in recent kernels (provided the BIOS has
the recent MTRR patches applied):
 ------------[ cut here ]------------
WARNING: at arch/x86/kernel/cpu/mtrr/main.c:1500 mtrr_trim_uncached_memory+0x382/0x384()
WARNING: strange, CPU MTRRs all blank?
Modules linked in:
Supported: Yes
Pid: 0, comm: swapper Not tainted 2.6.27.7-9-default #1
 [<c0106570>] dump_trace+0x6b/0x249
 [<c01070a5>] show_trace+0x20/0x39
 [<c0343c02>] dump_stack+0x71/0x76
 [<c012acb2>] warn_slowpath+0x6f/0x90
 [<c0542f8f>] mtrr_trim_uncached_memory+0x382/0x384
 [<c053f24d>] setup_arch+0x40d/0x639
 [<c053a6ac>] start_kernel+0x6b/0x31f
 =======================
 ---[ end trace 4eaa2a86a8e2da22 ]---

Handle common x86 MTRR reads and writes, but don't act on them.

Signed-off-by: Carl-Daniel Hailfinger <c-d.hailfinger.devel.2006@gmx.net>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6450 | malc | 2009-01-26 19:21:53 +0100 (Mo, 26 Jan 2009) | 1 line

R13 is reserved for small data area pointer by SVR4 PPC ABI
------------------------------------------------------------------------
r6451 | aliguori | 2009-01-26 20:37:41 +0100 (Mo, 26 Jan 2009) | 87 lines

Remove the advertising clause from the slirp license

According to the FSF, the 4-clause BSD license, which slirp is covered under,
is not compatible with the GPL or LGPL[1].

[1] http://www.fsf.org/licensing/licenses/index_html#GPLIncompatibleLicenses

There are three declared copyright holders in slirp that use the 4-clause
BSD license, the Regents of UC Berkley, Danny Gasparovski, and Kelly Price.
Below are the appropriate permissions to remove the advertise clause from slirp
from each party.

Special thanks go to Richard Fontana from Red Hat for contacting all of the
necessary authors to resolve this issue!

Regents of UC Berkley:
From ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change

July 22, 1999

To All Licensees, Distributors of Any Version of BSD:

As you know, certain of the Berkeley Software Distribution ("BSD") source
code files require that further distributions of products containing all or
portions of the software, acknowledge within their advertising materials
that such products contain software developed by UC Berkeley and its
contributors.

Specifically, the provision reads:

"     * 3. All advertising materials mentioning features or use of this software
      *    must display the following acknowledgement:
      *    This product includes software developed by the University of
      *    California, Berkeley and its contributors."

Effective immediately, licensees and distributors are no longer required to
include the acknowledgement within advertising materials.  Accordingly, the
foregoing paragraph of those BSD Unix files containing it is hereby deleted
in its entirety.

William Hoskins
Director, Office of Technology Licensing
University of California, Berkeley

Danny Gasparovski:

Subject: RE: Slirp license
Date: Thu, 8 Jan 2009 10:51:00 +1100
From: "Gasparovski, Daniel" <Daniel.Gasparovski@ato.gov.au>
To: "Richard Fontana" <rfontana@redhat.com>

Hi Richard,

I have no objection to having Slirp code in QEMU be licensed under the
3-clause BSD license.

Thanks for taking the effort to consult me about this.


Dan ...

Kelly Price:

Date: Thu, 8 Jan 2009 19:38:56 -0500
From: "Kelly Price" <strredwolf@gmail.com>
To: "Richard Fontana" <rfontana@redhat.com>
Subject: Re: Slirp license

Thanks for contacting me, Richard.  I'm glad you were able to find
Dan, as I've been "keeping the light on" for Slirp.  I have no use for
it now, and I have little time for it (now holding onto Keenspot's
Comic Genesis and having a regular US state government position). If
Dan would like to return to the project, I'd love to give it back to
him.

As for copyright, I don't own all of it.  Dan does, so I will defer to
him.  Any of my patches I will gladly license to the 3-part BSD
license.  My interest in re-licensing was because we didn't have ready
info to contact Dan.  If Dan would like to port Slirp back out of
QEMU, a lot of us 64-bit users would be grateful.

Feel free to share this email address with Dan.  I will be glad to
effect a transfer of the project to him and Mr. Bellard of the QEMU
project.

Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6452 | aliguori | 2009-01-26 20:54:31 +0100 (Mo, 26 Jan 2009) | 11 lines

Log reset events (Jan Kiszka)

Original idea&code by Kevin Wolf, split-up in two patches and added more
archs.

This patch introduces a flag to log CPU resets. Useful for tracing
unexpected resets (such as those triggered by x86 triple faults).

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6453 | aliguori | 2009-01-26 20:54:36 +0100 (Mo, 26 Jan 2009) | 10 lines

x86: Issue reset on triple faults (Jan Kiszka)

As discussed a few times on this list: A triple fault causes a system
reset on x86, and some guests make use of this (e.g. 386BSD). To keep
the chance of tracing unexpected resets, log them if CPU_LOG_RESET is
set.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6454 | aliguori | 2009-01-26 21:26:46 +0100 (Mo, 26 Jan 2009) | 9 lines

block-vpc: Split up struct vpc_subheader (Kevin Wolf)

struct vpc_subheader currently is a union of two completely different
data structures (the Hard Disk Footer and the Dynamic Disk Header).
That doesn't make too much sense, so split them up.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6455 | aliguori | 2009-01-26 21:26:49 +0100 (Mo, 26 Jan 2009) | 9 lines

block-vpc: Adapt header structures to official documentation (Kevin Wolf)

The current definition of the VirtualPC headers is incomplete and partly
even wrong. This patch changes the header structs according to the
official VHD specification.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6456 | aliguori | 2009-01-26 21:26:54 +0100 (Mo, 26 Jan 2009) | 8 lines

block-vpc: Fix disk size (Kevin Wolf)

VirtualPC bases the virtual disk size on the geometry rather than on
the size stored in the header.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6457 | aliguori | 2009-01-26 21:26:58 +0100 (Mo, 26 Jan 2009) | 7 lines

block-vpc: Use the qemu block layer (Kevin Wolf)

Instead of accessing the file directly, use the qemu block layer.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6458 | aliguori | 2009-01-26 21:27:02 +0100 (Mo, 26 Jan 2009) | 7 lines

block-vpc: Write support (Kevin Wolf)

Add write support for VHD images.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6459 | aliguori | 2009-01-26 21:27:06 +0100 (Mo, 26 Jan 2009) | 7 lines

block-vpc: Create images (Kevin Wolf)

Add an implementation to create VHD images.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6460 | aliguori | 2009-01-26 21:32:18 +0100 (Mo, 26 Jan 2009) | 15 lines

Check if the i8254 timer is active before deactivating it (Alexander Graf)

The HPET emulation can disable the i8254 when the HPET is
in legacy mode, thus emulating the i8254's behavior.

But if it does, the i8254 doesn't have to be running, so
let's check to see if the timer works and not disable it
if it's not.

This fixes a segmentation fault when running Mac OS X as
guest os.

Signed-off-by: Alexander Graf <agraf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6461 | aliguori | 2009-01-26 21:32:22 +0100 (Mo, 26 Jan 2009) | 12 lines

kvm-x86: Remove eflags conversion into emulator format (Jan Kiszka)

It seems that the conversion of the kernel-delivered eflags state into
qemu's internal split representation was once needed in an older kvm
design (register read-back may have taken place from inside cpu_exec).
Today it is plain wrong and causes incorrect cpu state reporting (gdb,
monitor) and should also corrupt its saving (savevm, migration). Drop
the related lines.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6462 | edgar_igl | 2009-01-26 22:47:27 +0100 (Mo, 26 Jan 2009) | 6 lines

ETRAX: Remove display-state argument from board init.

Apparently this board was forgotten in the display changes.

Signed-off-by: Edgar E. Iglesias <edgar.iglesias@gmail.com>

------------------------------------------------------------------------
r6463 | edgar_igl | 2009-01-26 23:21:30 +0100 (Mo, 26 Jan 2009) | 4 lines

CRIS: Init the feedback shiftreg used for randomizing TLB sets.

Signed-off-by: Edgar E. Iglesias <edgar.iglesias@gmail.com>

------------------------------------------------------------------------
r6464 | aliguori | 2009-01-27 15:29:15 +0100 (Di, 27 Jan 2009) | 7 lines

block-vpc: Fix support for images > 4 GB (Kevin Wolf)

This patch fixes the truncation of sector offsets to 32 bits.

Signed-off-by: Kevin Wolf <kwolf@suse.de>
Signed-off-by: Anthony Liguori <aliguori@us.ibm.com>

------------------------------------------------------------------------
r6465 | blueswir1 | 2009-01-27 20:15:31 +0100 (Di, 27 Jan 2009) | 1 line

Add Simba device ID
------------------------------------------------------------------------
r6466 | malc | 2009-01-28 18:16:56 +0100 (Mi, 28 Jan 2009) | 4 lines

Fix qemu_malloc.

make {linux,bsd}-user qemu_realloc handle ptr == NULL correctly.
spotted by malc.
------------------------------------------------------------------------